# Generated by Django 5.2.17 on 2026-09-30 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0002_main_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Kept if the account is later deleted.",
                        max_length=150,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Added"),
                            ("update", "Changed"),
                            ("delete", "Deleted"),
                            ("login", "Signed in"),
                            ("logout", "Signed out"),
                            ("login_failed", "Failed sign-in"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("app_label", models.CharField(blank=True, max_length=50)),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="record type",
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=50)),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=200, verbose_name="record"),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="branches.branch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "activity",
                "verbose_name_plural": "activity log",
                "ordering": ["-created_at", "-id"],
                "default_permissions": ("view",),
            },
        ),
    ]
