# Generated by Django 5.2.17 on 2026-09-30 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, help_text="e.g. Senior Veterinarian", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "licence_number",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="registration / licence number",
                    ),
                ),
                (
                    "can_attend",
                    models.BooleanField(
                        default=True,
                        help_text="Shown in the “Attended by” list on appointments. Untick for non-clinical staff.",
                        verbose_name="can attend appointments",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Decides what this person can see and do in the dashboard.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_profiles",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "staff profile",
            },
        ),
    ]
