# Generated by Django 5.2.17 on 2026-09-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profiles_for_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="all_branches",
            field=models.BooleanField(
                default=False,
                help_text="Can work in every branch, including ones added later. For owners and managers.",
                verbose_name="all branches",
            ),
        ),
    ]
