# Generated by Django 5.2.17 on 2026-09-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_staffprofile_all_branches"),
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="branches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Branches this person works at.",
                related_name="staff",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="default_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Where they start after signing in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="branches.branch",
            ),
        ),
    ]
