# Generated by Django 5.2.17 on 2026-09-30 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "appointments",
            "0006_plannedvaccination_plan_plannedvaccination_record_and_more",
        ),
        ("billing", "0005_branch_discounts"),
        ("branches", "0002_main_branch"),
        ("clients", "0002_pet_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("vaccination_due", "Vaccination reminder"),
                            ("follow_up", "Follow-up reminder"),
                            ("booking", "Booking confirmation"),
                            ("invoice", "Bill / receipt"),
                            ("general", "General message"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="For emails only.", max_length=150
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="You can use {client}, {pet}, {date}, {time}, {vaccine}, {invoice}, {amount}, {balance}, {hospital}, {branch} and {phone}."
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="in use")),
            ],
            options={
                "verbose_name": "message template",
                "ordering": ["purpose", "name"],
            },
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        max_length=10,
                    ),
                ),
                ("to", models.CharField(max_length=150)),
                ("subject", models.CharField(blank=True, max_length=150)),
                ("body", models.TextField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("vaccination_due", "Vaccination reminder"),
                            ("follow_up", "Follow-up reminder"),
                            ("booking", "Booking confirmation"),
                            ("invoice", "Bill / receipt"),
                            ("general", "General message"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("opened", "Opened in WhatsApp"),
                            ("logged", "Logged only (no provider set up)"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="logged",
                        max_length=10,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="branches.branch",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="clients.client",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clients.pet",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages sent",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
