# Generated by Django 5.2.17 on 2026-09-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExaminationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(editable=False, max_length=40, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "value_kind",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("choice", "Choice from a list"),
                        ],
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=30)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="safe range from",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="safe range to",
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True, help_text="For choice types: one option per line."
                    ),
                ),
                (
                    "normal_options",
                    models.TextField(
                        blank=True,
                        help_text="For choice types: the options that count as normal, one per line.",
                        verbose_name="normal options",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide this from the examination form.",
                        verbose_name="in use",
                    ),
                ),
            ],
            options={
                "verbose_name": "examination type",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HistoryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop offering this for new visits.",
                        verbose_name="in use",
                    ),
                ),
            ],
            options={
                "verbose_name": "history option",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop offering this for new visits.",
                        verbose_name="in use",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "species",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VaccinationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop offering this for new visits.",
                        verbose_name="in use",
                    ),
                ),
                (
                    "booster_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Used to suggest the next due date, e.g. 365 for a yearly booster.",
                        null=True,
                        verbose_name="booster interval (days)",
                    ),
                ),
            ],
            options={
                "verbose_name": "vaccination type",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
