# Generated by Django 5.2.17 on 2026-09-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_setup", "0002_fixed_examinations_and_species"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examinationtype",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "examination field",
                "verbose_name_plural": "examination fields",
            },
        ),
        migrations.AlterModelOptions(
            name="historyoption",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "history field",
                "verbose_name_plural": "history fields",
            },
        ),
        migrations.AlterModelOptions(
            name="species",
            options={"ordering": ["order", "name"], "verbose_name_plural": "species"},
        ),
        migrations.AlterModelOptions(
            name="vaccinationtype",
            options={"ordering": ["order", "name"], "verbose_name": "vaccination type"},
        ),
        migrations.AddField(
            model_name="historyoption",
            name="max_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="normal to",
            ),
        ),
        migrations.AddField(
            model_name="historyoption",
            name="min_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="normal from",
            ),
        ),
        migrations.AddField(
            model_name="historyoption",
            name="normal_options",
            field=models.TextField(
                blank=True,
                help_text="For a choice or yes/no: the answers that count as normal, one per line. Anything else is flagged.",
                verbose_name="normal options",
            ),
        ),
        migrations.AddField(
            model_name="historyoption",
            name="options",
            field=models.TextField(
                blank=True, help_text="For a choice: one option per line."
            ),
        ),
        migrations.AddField(
            model_name="historyoption",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first on the visit form."
            ),
        ),
        migrations.AddField(
            model_name="historyoption",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="For numbers, e.g. °C or beats/min.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="historyoption",
            name="value_kind",
            field=models.CharField(
                choices=[
                    ("number", "Number"),
                    ("choice", "Choice from a list"),
                    ("yesno", "Yes / No"),
                    ("text", "Free text"),
                ],
                default="text",
                max_length=10,
                verbose_name="value type",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first on the visit form."
            ),
        ),
        migrations.AddField(
            model_name="vaccinationtype",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first on the visit form."
            ),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="code",
            field=models.SlugField(editable=False, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Untick to hide this from the visit form.",
                verbose_name="in use",
            ),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="max_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="normal to",
            ),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="min_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="normal from",
            ),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="normal_options",
            field=models.TextField(
                blank=True,
                help_text="For a choice or yes/no: the answers that count as normal, one per line. Anything else is flagged.",
                verbose_name="normal options",
            ),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="options",
            field=models.TextField(
                blank=True, help_text="For a choice: one option per line."
            ),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first on the visit form."
            ),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="For numbers, e.g. °C or beats/min.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="examinationtype",
            name="value_kind",
            field=models.CharField(
                choices=[
                    ("number", "Number"),
                    ("choice", "Choice from a list"),
                    ("yesno", "Yes / No"),
                    ("text", "Free text"),
                ],
                default="text",
                max_length=10,
                verbose_name="value type",
            ),
        ),
    ]
