# Generated by Django 5.2.17 on 2026-09-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_setup", "0004_fields_from_paper_form"),
        ("shop", "0007_product_is_package_packageitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first on the visit form.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop offering this for new visits.",
                        verbose_name="in use",
                    ),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        help_text="Filled into the visit's diagnosis if it is still empty.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "treatment template",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TreatmentTemplateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        blank=True,
                        help_text="Blank uses the item's usual dose.",
                        max_length=60,
                    ),
                ),
                ("route", models.CharField(blank=True, max_length=60)),
                ("frequency", models.CharField(blank=True, max_length=60)),
                ("duration", models.CharField(blank=True, max_length=60)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="qty to bill",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("treatment_kind", ""), _negated=True
                        ),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shop.product",
                        verbose_name="catalogue item",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="clinic_setup.treatmenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "template line",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first on the visit form.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop offering this for new visits.",
                        verbose_name="in use",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank if it suits any species.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccination_plans",
                        to="clinic_setup.species",
                    ),
                ),
            ],
            options={
                "verbose_name": "vaccination plan",
                "ordering": ["order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanDose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="e.g. 1st dose, booster.", max_length=60
                    ),
                ),
                (
                    "days_after_start",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Days after the plan starts, e.g. 0, 21, 42.",
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clinic_setup.vaccinationtype",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="clinic_setup.vaccinationplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "dose",
                "ordering": ["days_after_start", "id"],
            },
        ),
    ]
