# Generated by Django 5.2.17 on 2026-09-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_treatment_item_treatment_quantity_and_more"),
        ("billing", "0003_sales_permissions_for_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Added by hand"),
                    ("treatment", "From treatment"),
                    ("visit_fee", "Visit fee"),
                ],
                default="",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_items",
                to="appointments.treatment",
            ),
        ),
    ]
