# Generated by Django 5.2.17 on 2026-09-30 15:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def bills_to_branches(apps, schema_editor):
    """Visit bills belong to the visit's branch; everything else so far to the main branch."""
    Branch = apps.get_model("branches", "Branch")
    Invoice = apps.get_model("billing", "Invoice")
    main = Branch.objects.filter(is_active=True).order_by("-is_main", "order", "id").first()
    for invoice in Invoice.objects.filter(branch__isnull=True).select_related("appointment"):
        invoice.branch_id = invoice.appointment.branch_id if invoice.appointment_id else main.pk
        invoice.save(update_fields=["branch"])


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_branch_triage_booking"),
        ("billing", "0004_invoiceitem_source_invoiceitem_treatment"),
        ("branches", "0002_main_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="discount %",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(
                blank=True, editable=False, max_length=30, verbose_name="invoice no."
            ),
        ),
        migrations.RunPython(bills_to_branches, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invoice",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="branches.branch"
            ),
        ),
    ]
