# Generated by Django 5.2.17 on 2026-09-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="visible on site"),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-paw",
                        help_text="Font Awesome icon name, e.g. fa-paw, fa-syringe, fa-tooth.",
                        max_length=50,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="services/")),
                (
                    "is_featured",
                    models.BooleanField(default=True, verbose_name="show on home page"),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
    ]
