# Generated by Django 5.2.17 on 2026-09-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_main_branch"),
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="The branch the visitor chose, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_messages",
                to="branches.branch",
            ),
        ),
    ]
