# Generated by Django 5.2.17 on 2026-09-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="visible on site"),
                ),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(blank=True, upload_to="hero/")),
                ("button_text", models.CharField(blank=True, max_length=40)),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        help_text="e.g. /contact/ or a full URL.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="BMB Veterinary Hospital & 24 Hrs Emergency Service",
                        max_length=150,
                    ),
                ),
                ("short_name", models.CharField(default="BMB Vets", max_length=60)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short description used in the footer and search results.",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Include the country code, e.g. +977 ...",
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("opening_hours", models.CharField(blank=True, max_length=120)),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Google Maps embed URL (the src of the embed iframe).",
                        max_length=1000,
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("about_heading", models.CharField(blank=True, max_length=150)),
                ("about_text", models.TextField(blank=True)),
                ("about_image", models.ImageField(blank=True, upload_to="site/")),
                ("philosophy_text", models.TextField(blank=True)),
                ("philosophy_image", models.ImageField(blank=True, upload_to="site/")),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="visible on site"),
                ),
                ("label", models.CharField(max_length=60)),
                ("value", models.PositiveIntegerField()),
                (
                    "suffix",
                    models.CharField(
                        blank=True, help_text="e.g. + or /7", max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "statistic",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
    ]
