# Generated by Django 5.2.17 on 2026-09-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="consent_text",
            field=models.TextField(
                blank=True,
                default="I am the owner, or the person responsible, for the animal described above. I authorise the veterinarians and staff of this hospital to examine and treat my pet as they consider necessary, including the use of medicines, anaesthesia and procedures explained to me. I understand that every treatment carries some risk and that no result can be guaranteed. I agree to pay the charges for the services provided.",
                help_text="Printed in the Authorization section of the visit form, above the owner's signature. Nepali text can be pasted here.",
                verbose_name="authorization text",
            ),
        ),
    ]
