# Generated by Django 5.2.17 on 2026-09-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_consent_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="default_vat_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Applied to new invoices; 0 if the hospital does not charge VAT.",
                max_digits=5,
                verbose_name="default VAT %",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="invoice_footer",
            field=models.CharField(
                blank=True,
                default="Thank you for choosing us. Get well soon!",
                help_text="A short line printed at the bottom of every invoice.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="pan_number",
            field=models.CharField(
                blank=True,
                help_text="Printed on invoices.",
                max_length=30,
                verbose_name="PAN / VAT no.",
            ),
        ),
    ]
