# Generated by Django 5.2.17 on 2026-09-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_default_vat_percent_and_more"),
        ("shop", "0003_treatmentitem_product_default_dose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="visit_fee_item",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g. the consultation fee. Leave blank to add fees by hand.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="shop.product",
                verbose_name="fee added to every visit bill",
            ),
        ),
    ]
