# Generated by Django 5.2.17 on 2026-09-29 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="visible on site"),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=110, unique=True)),
                (
                    "role",
                    models.CharField(
                        help_text="e.g. Veterinarian, Veterinary Technician",
                        max_length=100,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True, help_text="e.g. B.V.Sc. & A.H.", max_length=150
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="team/")),
                ("short_bio", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="team.teammember",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
