# Generated by Django 5.2.17 on 2026-09-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="visible on site"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Also used as the image's alternative text.",
                        max_length=150,
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
    ]
