# Generated by Django 5.2.17 on 2026-09-30 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(editable=False, max_length=110, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="shop/categories/")),
                (
                    "show_online",
                    models.BooleanField(
                        default=True,
                        help_text="Untick for things only sold at the counter, e.g. clinic services.",
                        verbose_name="show in the online shop",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True, verbose_name="in use")),
            ],
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(editable=False, max_length=160, unique=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Your own product code or barcode.",
                        max_length=50,
                        verbose_name="SKU / code",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "unit",
                    models.CharField(
                        default="piece",
                        help_text="How it is sold, e.g. piece, tablet, bottle, kg.",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="shop/products/")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="selling price"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Only shown to staff.",
                        max_digits=10,
                        null=True,
                        verbose_name="cost price",
                    ),
                ),
                (
                    "track_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Untick for services and anything you do not count, such as a consultation fee.",
                    ),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="in stock",
                    ),
                ),
                (
                    "low_stock_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Warn when stock falls to this.",
                        max_digits=10,
                        verbose_name="low-stock warning at",
                    ),
                ),
                (
                    "is_prescription",
                    models.BooleanField(
                        default=False,
                        help_text="Sold only after a vet's advice; shown as such online.",
                        verbose_name="prescription only",
                    ),
                ),
                (
                    "show_online",
                    models.BooleanField(
                        default=True, verbose_name="show in the online shop"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop selling it. Past invoices keep it.",
                        verbose_name="in use",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="shop.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [("adjust_stock", "Can adjust stock")],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="change"
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("opening", "Opening stock"),
                            ("purchase", "Stock received"),
                            ("sale", "Sold"),
                            ("sale_cancelled", "Sale cancelled"),
                            ("return", "Returned by customer"),
                            ("adjustment", "Stock count correction"),
                            ("damaged", "Damaged or expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="billing.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock movement",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
