# Generated by Django 5.2.17 on 2026-09-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_starter_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentItem",
            fields=[],
            options={
                "verbose_name": "treatment item",
                "verbose_name_plural": "treatment catalogue",
                "ordering": ["treatment_kind", "name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shop.product",),
        ),
        migrations.AddField(
            model_name="product",
            name="default_dose",
            field=models.CharField(
                blank=True, help_text="e.g. 10 mg/kg", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="default_duration",
            field=models.CharField(blank=True, help_text="e.g. 5 days", max_length=60),
        ),
        migrations.AddField(
            model_name="product",
            name="default_frequency",
            field=models.CharField(
                blank=True, help_text="e.g. twice a day", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="default_route",
            field=models.CharField(
                blank=True, help_text="e.g. oral, SC, IM, IV", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="treatment_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medicine", "Medicine"),
                    ("procedure", "Procedure"),
                    ("advice", "Advice"),
                ],
                help_text="Makes this item available in the Treatment tab of a visit. Leave blank for shop-only items.",
                max_length=10,
                verbose_name="use in treatments as",
            ),
        ),
    ]
