# Generated by Django 5.2.17 on 2026-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_treatment_catalogue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="treatment_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medicine", "Medicine"),
                    ("procedure", "Procedure"),
                    ("advice", "Advice"),
                ],
                help_text="Makes this item available in the Treatment tab of a visit. Leave blank for shop-only items.",
                max_length=10,
                verbose_name="treatment type",
            ),
        ),
    ]
