# Generated by Django 5.2.17 on 2026-09-30 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def stock_to_main_branch(apps, schema_editor):
    """Until now there was one stock count: it becomes the main branch's."""
    Branch = apps.get_model("branches", "Branch")
    Product = apps.get_model("shop", "Product")
    BranchStock = apps.get_model("shop", "BranchStock")
    StockMovement = apps.get_model("shop", "StockMovement")
    main = Branch.objects.filter(is_active=True).order_by("-is_main", "order", "id").first()
    if main is None:
        return
    BranchStock.objects.bulk_create(
        [
            BranchStock(product_id=pk, branch=main, quantity=quantity)
            for pk, quantity in Product.objects.filter(track_stock=True).values_list("pk", "stock_quantity")
        ]
    )
    StockMovement.objects.filter(branch__isnull=True).update(branch=main)


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0002_main_branch"),
        ("shop", "0005_alter_product_treatment_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="in stock (all branches)",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("opening", "Opening stock"),
                    ("purchase", "Stock received"),
                    ("sale", "Sold"),
                    ("sale_cancelled", "Sale cancelled"),
                    ("return", "Returned by customer"),
                    ("adjustment", "Stock count correction"),
                    ("damaged", "Damaged or expired"),
                    ("transfer_out", "Sent to another branch"),
                    ("transfer_in", "Received from another branch"),
                    ("transfer_back", "Transfer cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="transfer no.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "On the way"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="e.g. who is carrying it.", max_length=255
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "received_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="branches.branch",
                        verbose_name="from",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="branches.branch",
                        verbose_name="to",
                    ),
                ),
            ],
            options={
                "verbose_name": "stock transfer",
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("receive_stocktransfer", "Can receive stock transfers")
                ],
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="shop.stocktransfer",
            ),
        ),
        migrations.CreateModel(
            name="StockTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="shop.product",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.stocktransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="BranchPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="branch price"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="branches.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_prices",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "branch price",
                "ordering": ["product__name", "branch__order", "branch__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "branch"),
                        name="branchprice_unique_product_branch",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BranchStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="in stock",
                    ),
                ),
                (
                    "low_stock_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to use the product's level.",
                        max_digits=10,
                        null=True,
                        verbose_name="low-stock warning at",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="branches.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_stocks",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "branch stock",
                "ordering": ["branch__order", "branch__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "branch"),
                        name="branchstock_unique_product_branch",
                    )
                ],
            },
        ),
        migrations.RunPython(stock_to_main_branch, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="stockmovement",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="stock_movements", to="branches.branch"
            ),
        ),
    ]
