# Generated by Django 5.2.17 on 2026-09-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_branch_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_package",
            field=models.BooleanField(
                default=False,
                help_text="A bundle sold at one price, e.g. a puppy vaccination package. Selling it takes its contents from stock.",
                verbose_name="package",
            ),
        ),
        migrations.CreateModel(
            name="PackageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="in_packages",
                        to="shop.product",
                        verbose_name="item",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "package item",
                "ordering": ["id"],
            },
        ),
    ]
