# Generated by Django 5.2.17 on 2026-09-30 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic_setup", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="owner's name"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="phone")),
                (
                    "phone_digits",
                    models.CharField(db_index=True, editable=False, max_length=30),
                ),
                (
                    "alt_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="alternate phone"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="area / city"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(blank=True, max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "is_neutered",
                    models.BooleanField(
                        default=False, verbose_name="neutered / spayed"
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "dob_is_estimate",
                    models.BooleanField(
                        default=False, verbose_name="date of birth is approximate"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="colour and markings"
                    ),
                ),
                ("microchip_number", models.CharField(blank=True, max_length=50)),
                (
                    "alerts",
                    models.TextField(
                        blank=True,
                        help_text="Shown as a warning on every visit, e.g. “Allergic to penicillin”.",
                        verbose_name="allergies and alerts",
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="pets/")),
                (
                    "is_deceased",
                    models.BooleanField(default=False, verbose_name="deceased"),
                ),
                ("date_of_death", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="clients.client",
                        verbose_name="owner",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pets",
                        to="clinic_setup.species",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
    ]
