# Generated by Django 5.2.17 on 2026-09-30 16:00

import apps.clients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_branch_triage_booking"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PetDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lab", "Lab report"),
                            ("imaging", "X-ray / ultrasound"),
                            ("photo", "Photo"),
                            ("prescription", "Prescription"),
                            ("consent", "Consent form"),
                            ("referral", "Referral / letter"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="e.g. CBC 12 May, chest X-ray. Left blank, the file name is used.",
                        max_length=150,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=apps.clients.models.PrivateStorage(),
                        upload_to=apps.clients.models.document_path,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="appointments.appointment",
                        verbose_name="visit",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clients.pet",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pet document",
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
    ]
