# Generated by Django 5.2.17 on 2026-09-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0005_alter_product_treatment_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Chabahil", max_length=100, unique=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code used in invoice numbers, e.g. CBL. Letters and digits only.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="Include the country code, e.g. +977 ...",
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("opening_hours", models.CharField(blank=True, max_length=120)),
                (
                    "map_embed_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="map embed URL"
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the hospital's.",
                        max_length=30,
                        verbose_name="PAN / VAT no.",
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to use the hospital's.",
                        max_digits=5,
                        null=True,
                        verbose_name="VAT %",
                    ),
                ),
                (
                    "invoice_footer",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the hospital's.",
                        max_length=255,
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="main branch"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick when a branch closes. Its history is kept.",
                        verbose_name="open",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "visit_fee_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to use the hospital's.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="shop.product",
                        verbose_name="fee added to every visit bill",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "branches",
                "ordering": ["-is_main", "order", "name"],
            },
        ),
    ]
