# Generated by Django 5.2.17 on 2026-09-30 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("clinic_setup", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="appointment no.",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "token",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("waiting", "Waiting"),
                            ("in_consultation", "In consultation"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="reason for visit"),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="body weight (kg)",
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolved", "Resolved"),
                            ("improving", "Improving"),
                            ("ongoing", "Ongoing treatment"),
                            ("referred", "Referred"),
                            ("deceased", "Deceased"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result_notes",
                    models.TextField(blank=True, verbose_name="result notes"),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "attended_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attended_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="clients.client",
                        verbose_name="owner",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follow_up_of",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="clients.pet",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date", "token", "arrival_time", "id"],
                "permissions": [
                    ("view_clinical", "Can view clinical details"),
                    ("record_clinical", "Can record clinical details"),
                    ("change_completed_appointment", "Can edit completed appointments"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AppointmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, help_text="e.g. how long, how often", max_length=255
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic_setup.historyoption",
                        verbose_name="history",
                    ),
                ),
            ],
            options={
                "verbose_name": "history entry",
                "verbose_name_plural": "history",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ExaminationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=60)),
                (
                    "is_abnormal",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="outside normal range",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examinations",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic_setup.examinationtype",
                        verbose_name="examination",
                    ),
                ),
            ],
            options={
                "ordering": ["exam_type__order", "exam_type_id"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("medication", "Medication"),
                            ("procedure", "Procedure"),
                            ("advice", "Advice"),
                        ],
                        default="medication",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="medicine / procedure"
                    ),
                ),
                ("dose", models.CharField(blank=True, max_length=60)),
                (
                    "route",
                    models.CharField(
                        blank=True, help_text="e.g. oral, SC, IM, IV", max_length=60
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, help_text="e.g. twice a day", max_length=60
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g. 5 days", max_length=60
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="batch / lot no."
                    ),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinic_setup.vaccinationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "vaccination",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("token__isnull", False)),
                fields=("visit_date", "token"),
                name="appointment_unique_daily_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointmenthistory",
            constraint=models.UniqueConstraint(
                fields=("appointment", "option"),
                name="appointment_history_unique_option",
            ),
        ),
        migrations.AddConstraint(
            model_name="examinationresult",
            constraint=models.UniqueConstraint(
                fields=("appointment", "exam_type"),
                name="examination_result_unique_type",
            ),
        ),
    ]
