# Generated by Django 5.2.17 on 2026-09-30 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_value_grids"),
        ("shop", "0003_treatmentitem_product_default_dose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="item",
            field=models.ForeignKey(
                blank=True,
                help_text="Pick from the treatment catalogue to fill in the details and price.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments",
                to="shop.product",
                verbose_name="catalogue item",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="qty to bill"
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave blank for no charge.",
                max_digits=10,
                null=True,
                verbose_name="price",
            ),
        ),
    ]
