# Generated by Django 5.2.17 on 2026-09-30 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_branch_triage_booking"),
        ("clients", "0002_pet_documents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinationrecord",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="owner reminded"
            ),
        ),
        migrations.CreateModel(
            name="PlannedVaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=60)),
                ("due_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("given", "Given"),
                            ("skipped", "Skipped"),
                        ],
                        default="due",
                        max_length=10,
                    ),
                ),
                (
                    "reminded_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="owner reminded",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_vaccinations",
                        to="clients.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "planned vaccination",
                "ordering": ["due_date", "id"],
            },
        ),
    ]
