# Generated by Django 5.2.17 on 2026-09-30 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_vaccinationrecord_reminded_at_plannedvaccination"),
        ("clinic_setup", "0005_treatmenttemplate_treatmenttemplateline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedvaccination",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="clinic_setup.vaccinationplan",
            ),
        ),
        migrations.AddField(
            model_name="plannedvaccination",
            name="record",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="appointments.vaccinationrecord",
            ),
        ),
        migrations.AddField(
            model_name="plannedvaccination",
            name="vaccine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="clinic_setup.vaccinationtype",
            ),
        ),
    ]
