# Generated by Django 5.2.17 on 2026-10-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0002_main_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="from")),
                ("end_time", models.TimeField(verbose_name="to")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="branches.branch",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "doctor schedule",
                "verbose_name_plural": "doctor schedule",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("leave", "Leave / away"), ("extra", "Extra shift")],
                        default="leave",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(verbose_name="from date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for a single day.",
                        verbose_name="to date",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Leave the times blank for leave that lasts the whole day.",
                        null=True,
                        verbose_name="from time",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="to time"),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the extra shift is. Leave applies at every branch.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "leave or change",
                "verbose_name_plural": "leave & changes",
                "ordering": ["-start_date", "start_time"],
            },
        ),
    ]
